export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";

export const SEND_MEDIA = "SEND_MEDIA";
export const SEND_MEDIA_START = "SEND_MEDIA_START";
export const SEND_MEDIA_SUCCESS = "SEND_MEDIA_SUCCESS";
export const SEND_MEDIA_FAILED = "SEND_MEDIA_FAILED";

export const FETCH_CHAT = "FETCH_CHAT";
export const FETCH_CHAT_START = "FETCH_CHAT_START";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAILED = "FETCH_CHAT_FAILED";

